name: iRedemptFreedomMod
main: me.StevenLawson.TotalFreedomMod.TotalFreedomMod
version: 2.0
description: Plugin for the Total Freedom server.
softdepend: [BukkitTelnet, WorldEdit, Essentials]
authors: [Madgeek1450, Prozza, iHess, XGreenPlayz12]

# Plugin.YML (YAML) is no longer used to define commands
# due to CommandParameters, CommandPermissions, and TFM_Command
